# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 374)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.volume = QtWidgets.QSpinBox(Dialog)
        self.volume.setMaximum(999999999)
        self.volume.setObjectName("volume")
        self.gridLayout.addWidget(self.volume, 6, 1, 1, 1)
        self.ground = QtWidgets.QRadioButton(Dialog)
        self.ground.setChecked(True)
        self.ground.setObjectName("ground")
        self.gridLayout.addWidget(self.ground, 2, 1, 1, 1)
        self.deskr = QtWidgets.QLineEdit(Dialog)
        self.deskr.setObjectName("deskr")
        self.gridLayout.addWidget(self.deskr, 4, 1, 1, 1)
        self.obj = QtWidgets.QLineEdit(Dialog)
        self.obj.setObjectName("obj")
        self.gridLayout.addWidget(self.obj, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.price = QtWidgets.QSpinBox(Dialog)
        self.price.setMaximum(999999999)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.sort = QtWidgets.QLineEdit(Dialog)
        self.sort.setObjectName("sort")
        self.gridLayout.addWidget(self.sort, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 2, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 0, 1, 2)
        self.in_grains = QtWidgets.QRadioButton(Dialog)
        self.in_grains.setObjectName("in_grains")
        self.gridLayout.addWidget(self.in_grains, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить кофе"))
        self.label_3.setText(_translate("Dialog", "Молотый/в зёрнах"))
        self.ground.setText(_translate("Dialog", "Молотый"))
        self.label.setText(_translate("Dialog", "Введите сорт"))
        self.label_2.setText(_translate("Dialog", "Введите степень обжарки"))
        self.label_6.setText(_translate("Dialog", "Введите объём упаковки"))
        self.label_5.setText(_translate("Dialog", "Введите цену"))
        self.label_4.setText(_translate("Dialog", "Введите описание вкуса"))
        self.in_grains.setText(_translate("Dialog", "В зёрнах"))
